Traceback (most recent call last):
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/yuda/code/climatematch/course-content/venv/lib/python3.8/site-packages/nbclient/client.py", line 801, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 60 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# note this can take several minutes to download', "selected_vars = ['air_temperature_at_2_metres', 'northward_wind_at_10_metres', 'eastward_wind_at_10_metres',", "        'surface_air_pressure','sea_surface_temperature'] # the variables we want", "s3_data_ptrn = '{year}/{month}/data/{var}.nc' # path and filename format for this S3 bucket", "year_s3 = date_sel.strftime('%Y') # extract the year"]
...
['        ERA5_select=xr.merge([ERA5_select,ds_temp]) # if not empty, merge the new file', '    else:', '        ERA5_select=ds_temp #if empty, just assign the new file', '', 'ERA5_allvars = ERA5_select.sel(lon= slice(lon_range[0] , lon_range[1])).sel(lat = slice(lat_range[0] , lat_range[1]))']
-------------------

